# Theme configuration for P3 NOC

THEMES = [
    "terminal",
    "matrix-green",
    "amber-crt",
    "cyber-blue",
    "red-alert",
    "matrix",
    "bloomberg",
    "trading-desk",
    "midnight"
]

THEME_NAMES = {
    "terminal": "Terminal (Black/Red/Green)",
    "matrix-green": "Matrix Green",
    "amber-crt": "Amber CRT",
    "cyber-blue": "Cyber Blue",
    "red-alert": "Red Alert",
    "matrix": "Matrix",
    "bloomberg": "Bloomberg",
    "trading-desk": "Trading Desk",
    "midnight": "Midnight"
}

# Color configurations for manual rendering fallback (e.g. Rich console markup inside widgets)
THEME_COLORS = {
    "terminal": {
        "primary": "bright_green",
        "primary_bright": "bright_green",
        "muted": "grey50",
        "accent": "bright_red",
        "warning": "bright_red",
        "error": "red",
        "critical": "bright_red",
        "healthy": "bright_green",
        "tag": "[bold bright_green on black]",
        "tag_muted": "[green on black]",
    },
    "matrix-green": {
        "primary": "green",
        "primary_bright": "bright_green",
        "muted": "dark_green",
        "accent": "spring_green1",
        "warning": "yellow",
        "error": "red",
        "critical": "bright_red",
        "healthy": "green",
        "tag": "[bold green]",
        "tag_muted": "[green]",
    },
    "amber-crt": {
        "primary": "orange3",
        "primary_bright": "bright_yellow",
        "muted": "dark_orange",
        "accent": "gold1",
        "warning": "orange1",
        "error": "red",
        "critical": "bright_red",
        "healthy": "orange3",
        "tag": "[bold orange3]",
        "tag_muted": "[orange3]",
    },
    "cyber-blue": {
        "primary": "cyan",
        "primary_bright": "bright_cyan",
        "muted": "blue",
        "accent": "deep_sky_blue1",
        "warning": "yellow",
        "error": "magenta",
        "critical": "bright_magenta",
        "healthy": "cyan",
        "tag": "[bold cyan]",
        "tag_muted": "[cyan]",
    },
    "red-alert": {
        "primary": "red",
        "primary_bright": "bright_red",
        "muted": "dark_red",
        "accent": "orange_red1",
        "warning": "yellow",
        "error": "red",
        "critical": "bright_red",
        "healthy": "green",
        "tag": "[bold red]",
        "tag_muted": "[red]",
    },
    "matrix": {
        "primary": "bright_green",
        "primary_bright": "bright_green",
        "muted": "green",
        "accent": "spring_green1",
        "warning": "yellow",
        "error": "red",
        "critical": "bright_red",
        "healthy": "bright_green",
        "tag": "[bold bright_green]",
        "tag_muted": "[bright_green]",
    },
    "bloomberg": {
        "primary": "orange1",
        "primary_bright": "bright_yellow",
        "muted": "bright_blue",
        "accent": "gold1",
        "warning": "yellow",
        "error": "red",
        "critical": "bright_red",
        "healthy": "orange1",
        "tag": "[bold orange1]",
        "tag_muted": "[orange1]",
    },
    "trading-desk": {
        "primary": "cyan",
        "primary_bright": "bright_cyan",
        "muted": "grey50",
        "accent": "deep_sky_blue1",
        "warning": "yellow",
        "error": "magenta",
        "critical": "bright_magenta",
        "healthy": "cyan",
        "tag": "[bold cyan]",
        "tag_muted": "[cyan]",
    },
    "midnight": {
        "primary": "bright_white",
        "primary_bright": "bright_white",
        "muted": "grey37",
        "accent": "white",
        "warning": "grey70",
        "error": "bright_white",
        "critical": "bright_white",
        "healthy": "bright_white",
        "tag": "[bold bright_white]",
        "tag_muted": "[bright_white]",
    }
}
